import React, { useState, useEffect } from 'react';
import { Navbar } from './components/Navbar';
import { HeroGenerator } from './components/HeroGenerator';
import { SlideViewer } from './components/SlideViewer';
import { VirtualClassroom } from './components/VirtualClassroom';
import { InteractiveQuiz } from './components/InteractiveQuiz';
import { AITutorChat } from './components/AITutorChat';
import { CoursePayload } from './types';
import { PRESET_COURSES } from './data/defaultCourses';
import { exportCourseToPPTX } from './utils/pptxExport';
import { LanguageProvider, useLanguage } from './context/LanguageContext';

function AppContent() {
  const { t } = useLanguage();
  const [activeTab, setActiveTab] = useState<'generator' | 'slides' | 'classroom' | 'quiz'>('generator');
  const [coursesList, setCoursesList] = useState<CoursePayload[]>(PRESET_COURSES);
  const [currentCourse, setCurrentCourse] = useState<CoursePayload>(PRESET_COURSES[0]);
  const [currentSlideIndex, setCurrentSlideIndex] = useState<number>(0);
  const [isExporting, setIsExporting] = useState<boolean>(false);
  const [isTutorOpen, setIsTutorOpen] = useState<boolean>(false);
  const [isFullscreen, setIsFullscreen] = useState<boolean>(false);
  const [sessionCode] = useState<string>(() => `EDUVIBE-${Math.floor(1000 + Math.random() * 9000)}`);

  // Handle Fullscreen toggle
  const toggleFullscreen = () => {
    if (!document.fullscreenElement) {
      document.documentElement.requestFullscreen().then(() => setIsFullscreen(true)).catch(() => {});
    } else {
      document.exitFullscreen().then(() => setIsFullscreen(false)).catch(() => {});
    }
  };

  useEffect(() => {
    const handleFsChange = () => {
      setIsFullscreen(Boolean(document.fullscreenElement));
    };
    document.addEventListener('fullscreenchange', handleFsChange);
    return () => document.removeEventListener('fullscreenchange', handleFsChange);
  }, []);

  // Export to PowerPoint PPTX
  const handleExportPPTX = async () => {
    setIsExporting(true);
    try {
      await exportCourseToPPTX(currentCourse);
    } catch (error) {
      console.error('Failed to export PPTX:', error);
    } finally {
      setIsExporting(false);
    }
  };

  // When a new course is generated by AI
  const handleCourseGenerated = (newCourse: CoursePayload) => {
    setCoursesList((prev) => [newCourse, ...prev]);
    setCurrentCourse(newCourse);
    setCurrentSlideIndex(0);
    // Switch directly to slide viewer to view results!
    setActiveTab('slides');
  };

  const handleSelectPreset = (course: CoursePayload) => {
    setCurrentCourse(course);
    setCurrentSlideIndex(0);
    setActiveTab('slides');
  };

  const handleUpdateCourse = (updated: CoursePayload) => {
    setCurrentCourse(updated);
    setCoursesList((prev) => prev.map((c) => (c.id === updated.id ? updated : c)));
  };

  const currentSlide = currentCourse.slides[currentSlideIndex] || currentCourse.slides[0];

  return (
    <div className="min-h-screen bg-slate-50 text-slate-800 flex flex-col font-sans selection:bg-indigo-600 selection:text-white">
      {/* Top Navigation */}
      <Navbar
        activeTab={activeTab}
        setActiveTab={setActiveTab}
        currentCourse={currentCourse}
        coursesList={coursesList}
        onSelectCourse={(c) => {
          setCurrentCourse(c);
          setCurrentSlideIndex(0);
        }}
        onExportPPTX={handleExportPPTX}
        isExporting={isExporting}
        onToggleTutor={() => setIsTutorOpen(!isTutorOpen)}
        isTutorOpen={isTutorOpen}
        isFullscreen={isFullscreen}
        onToggleFullscreen={toggleFullscreen}
        sessionCode={sessionCode}
      />

      {/* Main Content Body */}
      <main className="flex-1 w-full pb-16">
        {activeTab === 'generator' && (
          <HeroGenerator
            onCourseGenerated={handleCourseGenerated}
            onSelectPreset={handleSelectPreset}
            currentCourse={currentCourse}
          />
        )}

        {activeTab === 'slides' && (
          <SlideViewer
            course={currentCourse}
            onUpdateCourse={handleUpdateCourse}
            onExportPPTX={handleExportPPTX}
            isExporting={isExporting}
            currentSlideIndex={currentSlideIndex}
            setCurrentSlideIndex={setCurrentSlideIndex}
          />
        )}

        {activeTab === 'classroom' && (
          <VirtualClassroom
            course={currentCourse}
            sessionCode={sessionCode}
            currentSlideIndex={currentSlideIndex}
            setCurrentSlideIndex={setCurrentSlideIndex}
          />
        )}

        {activeTab === 'quiz' && (
          <InteractiveQuiz
            course={currentCourse}
          />
        )}
      </main>

      {/* Floating AI Tutor Coach Widget */}
      <AITutorChat
        isOpen={isTutorOpen}
        onClose={() => setIsTutorOpen(false)}
        course={currentCourse}
        currentSlide={currentSlide}
      />

      {/* Footer */}
      <footer className="border-t border-slate-200 bg-white py-6 px-4 text-center text-xs text-slate-500 shadow-xs">
        <div className="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-3">
          <p className="font-medium text-slate-600">
            {t('footer.copyright')}
          </p>
          <div className="flex items-center gap-4 text-slate-500 font-medium">
            <span>{t('footer.poweredBy')}</span>
            <span className="text-slate-300">•</span>
            <span>{t('footer.nativePptx')}</span>
            <span className="text-slate-300">•</span>
            <span>{t('footer.jitsiVideo')}</span>
          </div>
        </div>
      </footer>
    </div>
  );
}

export default function App() {
  return (
    <LanguageProvider>
      <AppContent />
    </LanguageProvider>
  );
}

