import React, { useState, useEffect } from 'react';
import { Navbar } from './components/Navbar';
import { HeroGenerator } from './components/HeroGenerator';
import { SlideViewer } from './components/SlideViewer';
import { VirtualClassroom } from './components/VirtualClassroom';
import { InteractiveQuiz } from './components/InteractiveQuiz';
import { GroupsDashboard } from './components/GroupsDashboard';
import { AITutorChat } from './components/AITutorChat';
import { SettingsModal } from './components/SettingsModal';
import { ProfileModal } from './components/ProfileModal';
import { AuthScreen } from './components/AuthScreen';
import { CoursePayload } from './types';
import { PRESET_COURSES } from './data/defaultCourses';
import { exportCourseToPPTX } from './utils/pptxExport';
import { LanguageProvider, useLanguage } from './context/LanguageContext';
import { AuthAndGroupProvider, useAuthAndGroup } from './context/AuthAndGroupContext';

const STORAGE_KEY_COURSES = 'eduvibe_courses_v2';

function AppContent() {
  const { t } = useLanguage();
  const { isAuthenticated, currentUser, selectedViewProfile, setSelectedViewProfile, joinGroupByCode } = useAuthAndGroup();

  const [activeTab, setActiveTab] = useState<'generator' | 'slides' | 'classroom' | 'quiz' | 'groups'>('generator');
  
  // Persistent courses from localStorage
  const [coursesList, setCoursesList] = useState<CoursePayload[]>(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY_COURSES);
      if (saved) {
        const parsed = JSON.parse(saved);
        if (Array.isArray(parsed) && parsed.length > 0) {
          return parsed;
        }
      }
    } catch {
      // ignore
    }
    return PRESET_COURSES;
  });

  const [currentCourse, setCurrentCourse] = useState<CoursePayload>(() => coursesList[0] || PRESET_COURSES[0]);
  const [currentSlideIndex, setCurrentSlideIndex] = useState<number>(0);
  const [isExporting, setIsExporting] = useState<boolean>(false);
  const [isTutorOpen, setIsTutorOpen] = useState<boolean>(false);
  const [isSettingsOpen, setIsSettingsOpen] = useState<boolean>(false);
  const [isMyProfileOpen, setIsMyProfileOpen] = useState<boolean>(false);
  const [hasCustomKey, setHasCustomKey] = useState<boolean>(() => {
    return Boolean(localStorage.getItem('eduvibe_gemini_api_key'));
  });
  const [isFullscreen, setIsFullscreen] = useState<boolean>(false);
  const [sessionCode] = useState<string>(() => `EDUVIBE-${Math.floor(1000 + Math.random() * 9000)}`);

  // Detect ?join=CODE in URL query params on load
  useEffect(() => {
    if (typeof window !== 'undefined') {
      const params = new URLSearchParams(window.location.search);
      const joinCode = params.get('join');
      if (joinCode && isAuthenticated) {
        joinGroupByCode(joinCode).then((res) => {
          if (res.success) {
            setActiveTab('groups');
            alert(`🎉 ${res.message}`);
          }
        });
      }
    }
  }, [isAuthenticated]);

  // Persist coursesList to localStorage
  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY_COURSES, JSON.stringify(coursesList));
    } catch {
      // ignore
    }
  }, [coursesList]);

  // Handle Fullscreen toggle
  const toggleFullscreen = () => {
    if (!document.fullscreenElement) {
      document.documentElement.requestFullscreen().then(() => setIsFullscreen(true)).catch(() => {});
    } else {
      document.exitFullscreen().then(() => setIsFullscreen(false)).catch(() => {});
    }
  };

  useEffect(() => {
    const handleFsChange = () => {
      setIsFullscreen(Boolean(document.fullscreenElement));
    };
    document.addEventListener('fullscreenchange', handleFsChange);
    return () => document.removeEventListener('fullscreenchange', handleFsChange);
  }, []);

  // If not logged in, show Auth Gate
  if (!isAuthenticated) {
    return <AuthScreen />;
  }

  // Export to PowerPoint PPTX
  const handleExportPPTX = async () => {
    setIsExporting(true);
    try {
      await exportCourseToPPTX(currentCourse);
    } catch (error) {
      console.error('Failed to export PPTX:', error);
    } finally {
      setIsExporting(false);
    }
  };

  // When a new course is generated by AI
  const handleCourseGenerated = (newCourse: CoursePayload) => {
    setCoursesList((prev) => [newCourse, ...prev]);
    setCurrentCourse(newCourse);
    setCurrentSlideIndex(0);
    // Switch directly to slide viewer to view results!
    setActiveTab('slides');
  };

  const handleSelectPreset = (course: CoursePayload) => {
    setCurrentCourse(course);
    setCurrentSlideIndex(0);
    setActiveTab('slides');
  };

  const handleUpdateCourse = (updated: CoursePayload) => {
    setCurrentCourse(updated);
    setCoursesList((prev) => prev.map((c) => (c.id === updated.id ? updated : c)));
  };

  const handleImportCourses = (imported: CoursePayload[]) => {
    setCoursesList((prev) => [...imported, ...prev]);
    if (imported.length > 0) {
      setCurrentCourse(imported[0]);
      setCurrentSlideIndex(0);
      setActiveTab('slides');
    }
  };

  const handleResetCourses = () => {
    setCoursesList(PRESET_COURSES);
    setCurrentCourse(PRESET_COURSES[0]);
    setCurrentSlideIndex(0);
  };

  const currentSlide = currentCourse.slides[currentSlideIndex] || currentCourse.slides[0];

  return (
    <div className="min-h-screen bg-slate-50 text-slate-800 flex flex-col font-sans selection:bg-indigo-600 selection:text-white">
      {/* Top Navigation */}
      <Navbar
        activeTab={activeTab}
        setActiveTab={setActiveTab}
        currentCourse={currentCourse}
        coursesList={coursesList}
        onSelectCourse={(c) => {
          setCurrentCourse(c);
          setCurrentSlideIndex(0);
        }}
        onExportPPTX={handleExportPPTX}
        isExporting={isExporting}
        onToggleTutor={() => setIsTutorOpen(!isTutorOpen)}
        isTutorOpen={isTutorOpen}
        isFullscreen={isFullscreen}
        onToggleFullscreen={toggleFullscreen}
        sessionCode={sessionCode}
        onOpenSettings={() => setIsSettingsOpen(true)}
        onOpenProfile={() => setIsMyProfileOpen(true)}
        hasCustomKey={hasCustomKey}
      />

      {/* Main Content Body */}
      <main className="flex-1 w-full pb-16">
        {activeTab === 'generator' && (
          <HeroGenerator
            onCourseGenerated={handleCourseGenerated}
            onSelectPreset={handleSelectPreset}
            currentCourse={currentCourse}
          />
        )}

        {activeTab === 'slides' && (
          <SlideViewer
            course={currentCourse}
            onUpdateCourse={handleUpdateCourse}
            onExportPPTX={handleExportPPTX}
            isExporting={isExporting}
            currentSlideIndex={currentSlideIndex}
            setCurrentSlideIndex={setCurrentSlideIndex}
          />
        )}

        {activeTab === 'classroom' && (
          <VirtualClassroom
            course={currentCourse}
            coursesList={coursesList}
            onSelectCourse={(c) => {
              setCurrentCourse(c);
              setCurrentSlideIndex(0);
            }}
            sessionCode={sessionCode}
            currentSlideIndex={currentSlideIndex}
            setCurrentSlideIndex={setCurrentSlideIndex}
          />
        )}

        {activeTab === 'quiz' && (
          <InteractiveQuiz
            course={currentCourse}
          />
        )}

        {activeTab === 'groups' && (
          <GroupsDashboard
            onStartVisio={(grp) => {
              setActiveTab('classroom');
            }}
          />
        )}
      </main>

      {/* Floating AI Tutor Coach Widget */}
      <AITutorChat
        isOpen={isTutorOpen}
        onClose={() => setIsTutorOpen(false)}
        course={currentCourse}
        currentSlide={currentSlide}
      />

      {/* Settings & API Key Modal */}
      <SettingsModal
        isOpen={isSettingsOpen}
        onClose={() => setIsSettingsOpen(false)}
        coursesList={coursesList}
        onImportCourses={handleImportCourses}
        onResetCourses={handleResetCourses}
        onApiKeyChange={(hasKey) => setHasCustomKey(hasKey)}
      />

      {/* Edit My Profile Modal */}
      <ProfileModal
        isOpen={isMyProfileOpen}
        onClose={() => setIsMyProfileOpen(false)}
        targetProfile={currentUser}
      />

      {/* View Another Member's Profile Modal */}
      <ProfileModal
        isOpen={Boolean(selectedViewProfile)}
        onClose={() => setSelectedViewProfile(null)}
        targetProfile={selectedViewProfile}
      />

      {/* Footer */}
      <footer className="border-t border-slate-200 bg-white py-6 px-4 text-center text-xs text-slate-500 shadow-xs">
        <div className="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-3">
          <p className="font-medium text-slate-600">
            {t('footer.copyright')}
          </p>
          <div className="flex items-center gap-4 text-slate-500 font-medium">
            <span>{t('footer.poweredBy')}</span>
            <span className="text-slate-300">•</span>
            <span>{t('footer.nativePptx')}</span>
            <span className="text-slate-300">•</span>
            <span>{t('footer.jitsiVideo')}</span>
          </div>
        </div>
      </footer>
    </div>
  );
}

export default function App() {
  return (
    <LanguageProvider>
      <AuthAndGroupProvider>
        <AppContent />
      </AuthAndGroupProvider>
    </LanguageProvider>
  );
}
